version: '3.8'
services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
          - "9000:9000"
          - "25565:25565"
      depends_on:
          - vantagedb

  vantagedb:
      image: postgres:13
      environment:
          POSTGRES_USER: "vantage"
          POSTGRES_PASSWORD: "vantage"
          POSTGRES_DB: "vantage"
      ports:
          - "5432:5432"